#!/bin/bash

# Henter et oidc token for gitt servicebruker.
# Forutsetter at du er logget inn i vault
# Krever:
#   - kubectl
#   - kubectx
#   - jq
#   - vault

# Setter context til preprod slik at man ikke roter med prod
kubectx preprod-fss > /dev/null

# Setter opp port forward mot security token service med en refferanse til 
# jobben for å kunne drepe den
kubectl port-forward svc/security-token-service 9001:80 > /dev/null & sleep 2;
PID1=$!

# Henter creds fra vault og plukker ut basic auth creds
CREDS=$(HTTPS_PROXY=socks5://localhost:14122 \
    vault read /serviceuser/data/dev/$1 \
    | sed -n -E 's/.+password:(.+) username:(.+)]/\2:\1/p')
AUTH=$(printf "$CREDS" | base64)

# Gjør kall mot forwarda tjeneste med auth
RESP=$(curl -s -X GET \
    "http://localhost:9001/rest/v1/sts/token?grant_type=client_credentials&scope=openid" \
    -H "Authorization: Basic $AUTH")

# Henter access token fra response og kopierer det
echo $RESP | jq -r .access_token | pbcopy
echo "copied token"
# Dreper port forward
kill -9 $PID1
